version: '3'
services:
  backend:
    image: my_backend_image
    ports:
      - "5000:5000"
    environment:
      - WS_BACK_URL=http://backend:5000
      - SOME_OTHER_VARIABLE=value
    volumes:
      - ./logs:/app/back/logs

  frontend:
    image: my_frontend_image
    ports:
      - "80:80"
    environment:
      - WS_BACK_URL=http://backend:5000
